// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { InferenceAccount } from "./InferenceAccount";

export type GetAccountResponse = {/**
 * Application identity. In Mantle remote-control mode this is the real ChatGPT account.
 */
account: Account | null, /**
 * Inference identity, separate from remote-control login. Omitted outside dual-identity mode.
 */
inference?: InferenceAccount, requiresOpenaiAuth: boolean};
