// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";

/**
 * The provider that actually executes and bills model requests.
 */
export type InferenceAccount = { modelProvider: string, account: Account | null, requiresOpenaiAuth: boolean, };
